package main

import (
	"context"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/goccy/googlesqlite/internal/specmeta"
)

func init() {
	register(command{
		name:    "check",
		summary: "validate every spec, regenerate INDEX.md, and report integrity issues",
		run:     runCheck,
	})
}

const indexPath = "docs/specs/INDEX.md"

func runCheck(_ context.Context, args []string) error {
	flags := flag.NewFlagSet("check", flag.ContinueOnError)
	checkOnly := flags.Bool("check", false, "fail if INDEX.md is stale instead of writing it")
	if err := flags.Parse(args); err != nil {
		return err
	}

	root, err := projectRoot()
	if err != nil {
		return err
	}
	specs, err := specmeta.LoadAllSpecs(root)
	if err != nil {
		return fmt.Errorf("load specs: %w", err)
	}

	// 1. Validate every spec file. validate is the per-file check; we
	//    invoke its core inline so this command exits non-zero on the
	//    first integrity issue rather than relying on a subprocess.
	var validateErrs int
	for _, sp := range specs {
		data, err := os.ReadFile(filepath.Join(root, sp.Path))
		if err != nil {
			fmt.Fprintf(os.Stderr, "%s: %v\n", sp.Path, err)
			validateErrs++
			continue
		}
		for _, msg := range validateSpecBytes(data) {
			fmt.Fprintf(os.Stderr, "%s: %s\n", sp.Path, msg)
			validateErrs++
		}
	}

	// 2. Regenerate INDEX.md from spec frontmatter.
	idx := renderIndex(specs)
	indexAbs := filepath.Join(root, indexPath)
	currentRaw, _ := os.ReadFile(indexAbs)
	current := string(currentRaw)

	switch {
	case current == idx:
		fmt.Printf("check: %s up to date\n", indexPath)
	case *checkOnly:
		fmt.Fprintf(os.Stderr, "check: %s is stale; run `make spec/check` to regenerate\n", indexPath)
		validateErrs++
	default:
		if err := os.WriteFile(indexAbs, []byte(idx), 0o644); err != nil {
			return err
		}
		fmt.Printf("check: %s regenerated\n", indexPath)
	}

	// 3. Coverage integrity (orphan testdata + status mismatch).
	report := buildCoverageReport(root, specs)
	if len(report.statusMismatch) > 0 {
		fmt.Fprintf(os.Stderr, "check: %d spec(s) claim status=tested|implemented but lack usable testdata\n", len(report.statusMismatch))
		validateErrs++
	}
	if len(report.testdataNoSpec) > 0 {
		fmt.Fprintf(os.Stderr, "check: %d orphan testdata file(s) point to missing specs\n", len(report.testdataNoSpec))
		validateErrs++
	}

	if validateErrs > 0 {
		return fmt.Errorf("%d issue(s)", validateErrs)
	}
	fmt.Printf("check: %d spec(s) OK\n", len(specs))
	return nil
}

// renderIndex produces the canonical INDEX.md body. The index is
// grouped by dialect → category and lists every spec with its status
// and a link to the markdown.
func renderIndex(specs []specmeta.Spec) string {
	type entry struct {
		name   string
		status specmeta.Status
		path   string
	}
	type catBucket struct {
		name    string
		entries []entry
		ready   int
	}
	type dialectBucket struct {
		name  string
		cats  []*catBucket
		total int
		ready int
	}

	dByName := map[string]*dialectBucket{}
	dialectKeys := []string{}
	for _, sp := range specs {
		fm := sp.Frontmatter
		d := dByName[fm.Dialect]
		if d == nil {
			d = &dialectBucket{name: fm.Dialect}
			dByName[fm.Dialect] = d
			dialectKeys = append(dialectKeys, fm.Dialect)
		}
		var cb *catBucket
		for _, c := range d.cats {
			if c.name == fm.Category {
				cb = c
				break
			}
		}
		if cb == nil {
			cb = &catBucket{name: fm.Category}
			d.cats = append(d.cats, cb)
		}
		cb.entries = append(cb.entries, entry{name: fm.Name, status: fm.Status, path: sp.Path})
		d.total++
		if fm.Status == specmeta.StatusImplemented || fm.Status == specmeta.StatusTested {
			cb.ready++
			d.ready++
		}
	}
	sort.Strings(dialectKeys)

	var b strings.Builder
	b.WriteString("# Spec index\n\n")
	b.WriteString("_Auto-generated by `make spec/check`. Do not edit by hand._\n\n")
	for _, dk := range dialectKeys {
		d := dByName[dk]
		fmt.Fprintf(&b, "## %s — %d / %d (%s)\n\n", d.name, d.ready, d.total, percentText(d.ready, d.total))
		sort.Slice(d.cats, func(i, j int) bool { return d.cats[i].name < d.cats[j].name })
		for _, c := range d.cats {
			sort.Slice(c.entries, func(i, j int) bool { return c.entries[i].name < c.entries[j].name })
			fmt.Fprintf(&b, "### %s — %d / %d\n\n", c.name, c.ready, len(c.entries))
			for _, e := range c.entries {
				fmt.Fprintf(&b, "- [%s](%s) — %s\n", e.name, relativeFromIndex(e.path), e.status)
			}
			b.WriteString("\n")
		}
	}
	return b.String()
}

// relativeFromIndex builds an INDEX.md-relative link target. The
// index lives at docs/specs/INDEX.md; spec paths are project-root
// relative ("docs/specs/..."), so we just trim the shared prefix.
func relativeFromIndex(specPath string) string {
	const prefix = "docs/specs/"
	if after, ok := strings.CutPrefix(specPath, prefix); ok {
		return after
	}
	return specPath
}
